# Generated by Django 5.1.1 on 2024-10-05 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_payment_invoice_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='payment',
            name='email_id',
            field=models.EmailField(default='aaa@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_no',
            field=models.CharField(default=7986769879, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(default='mani', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.client'),
        ),
    ]
